phrase = "Night Academy"

print("\n")
print(phrase)
print("\n")
print(phrase + " is cool")
print("\n")
print(phrase.lower())
print("\n")
print(phrase.upper())
print("\n")
print(phrase.isupper())
print("\n")
print(phrase.upper().isupper())
print("\n")
print(len(phrase))
print("\n")
print(phrase[0])
print("\n") 
print(phrase.index("Night"))
print("\n")
print(phrase.replace("Night","Claw"))
print("\n")